import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 9.75

[font.normal]
family = "ShureTechMono Nerd Font"

[cursor]
style = { shape = "Beam" }

[shell]
program = "tmux"
args = ["new", "-A"]

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },
]

[window]
startup_mode = "Maximized"
